# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose port if necessary (not needed for stdio MCP server)

# Set the startup command
CMD [ "npm", "start" ]
